### ISSUE TITLE
OTAA keys vs ABP keys

### ISSUE THREAD

**Issue by hwater** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#11]
Hello Björn

gerade ist mir diese Zeile aufgefallen:
`    //lora.setKey("ABP-yourNetworkSKey", "ABP-yourappSKey", "OTAAyourAppKey);   //for OTAA
`
sollte das hier nicht lauten:
`    //lora.setKey("OTAA-yourNetworkSKey", "OTAA-yourappSKey", "OTAA-yourAppKey");   //for OTAA
`
das ist zwar eine Kommentarzeile, aber es sollten doch jeweils die richtigen Keys eingesetzt werden, oder?
Ich benötige also jeweils 2 Devices im TTN und auch 2 Versionen für den M5Stack - oder sehe ich das falsch?

Mit freundlichen Grüßen
Holger

**Comment by Bjoerns-TB** [comment]
Hallo Holger,

ja du siehst es ganz falsch ;-) ist auch kein einfaches Thema.

Der Tester arbeitet fast  nur mit ABP, OTAA macht hier keinen Sinn. Nur im OTAA Modus wird dieses auch verwendet. Somit brauchst du mindestens ein ABP Device und zusätzlich bei Bedarf ein OTAA Device. Neben der setKey Anwseisung, gibt es noch die setID Anweisung. Auf diese verteilen sich die Daten für ABP und OTAA. Es braucht also auch nur einen M5Stack

`    lora.setId("yourdeviceaddress", NULL, NULL);            //for ABP`
   ` //lora.setId("ABP-yourdeviceaddress", "OTAA-yourdeviceEUI", "OTAA-yourAppEUI"); //for OTAA`
   ` lora.setKey("yourNetworkSKey", "yourappSKey", NULL);          //for ABP`
    `//lora.setKey("ABP-yourNetworkSKey", "ABP-yourappSKey", "OTAAyourAppKey);   //for OTAA`

Danach sieht es dann so aus für ABP only:
`    lora.setId("xxxxxxxx", NULL, NULL);`
   ` lora.setKey("xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", NULL);`

Danach sieht es dann so aus für ABP + OTAA:
`    lora.setId("xxxxxxxx", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy");`
   ` lora.setKey("xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyy");`

Die Platzhalter mit x stehen für die ABP Keys/IDs und die mit y für die OTAA Keys/IDs.

Jetzt sollte eigentlich alles klar sein.
Grüße,
Björn

**Comment by hwater** [comment]
Moin Björn,
ja so wird es viel deutlicher.
Danke für die Aufklärung

Mit freundlichen Grüßen
Holger Watermann

> Am 10.03.2021 um 08:17 schrieb Björn Amann <notifications@github.com>:
> 
> Danach sieht es dann so aus für ABP + OTAA:
> lora.setId("xxxxxxxx", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy");
> lora.setKey("xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyy");
> 
> Die Platzhalter mit x stehen für die ABP Keys/IDs und die mit y für die OTAA Keys/IDs.
> 
> Jetzt sollte eigentlich alles klar sein.
> Grüße,
> Björn
> 



Holger Watermann


This message may contain confidential and privileged material for the sole use of the intended recipient. Any unauthorized review, use or distribution by others is strictly prohibited. If you have received the message by mistake, please advise the sender by reply email and delete the message. Thank you very much for decoding this tiny fontface
