### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Byte1122** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#2]
I cant compile it for the M5stack fire esp32

" 'include' was not declared in this scope "
 
In networktester.ino, line 803:
" isf = 0;include "LoRa.h" "

Error message:

networktester.ino:52:56: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

> .../M5Stack-LoRaWAN-Network-Tester-master/networktester/networktester.ino:52:56: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

 char *dr[6] = {"DR5", "DR4", "DR3", "DR2", "DR1", "DR0"};

**Comment by Bjoerns-TB** [comment]
There is no include in line 803, and i don't use LoRa.h, please.
