### ISSUE TITLE
'class LoRaWanClass' has no member named 'setDutyCycle'

### ISSUE THREAD

**Issue by FrankUlbrich** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#3]
Hello Bjoern,

I would like to compile your Code today with ARDUINO IDE 1.8.10, but I get into trouble with this error message.
'class LoRaWanClass' has no member named 'setDutyCycle'

Maybe I need a special library. Can you help me out ?

Best regards Frank

**Comment by FrankUlbrich** [comment]
`  
exit status 1
'class LoRaWanClass' has no member named 'setDutyCycle'
`

**Comment by FrankUlbrich** [comment]
` */
#include <M5Stack.h>				//  https://github.com/m5stack/M5Stack  Version 0.3.0
#include <M5_UI.h>					//  https://github.com/dsiberia9s/M5_UI Version 2.5.7
#include <LoRaWan.h>
#include "soc/timer_group_struct.h"
#include "soc/timer_group_reg.h"

#define M5go
#define M5gps

`

**Comment by FrankUlbrich** [comment]
Maybe a special version of M5Stack is required ?

**Comment by Bjoerns-TB** [comment]
Hi Frank,


just replace the original files LoraWan.h and LoRaWan.cpp delivered by the M5Stack Library under M5Stack/src with the ones in the src directory. Delete the src directory afterwards or move it.

Greetings,
Björn

**Comment by FrankUlbrich** [comment]
Hallo Björn,
danke für die schnelle Antwort.

I have now the following Libraries isntalled:
   M5Stack         Version 0.2.9
    TinyGPSPlus     Version 1.0.2
    NeoPixelBus     Version 2.5.7

I MOVED the modified Lora Files to libraries/M5Stack/src   and the compilation works now.
I had to overwrite the original files in the libraries directory.
I guess moving is importing.

Vielen Dank,
Frank

**Comment by FrankUlbrich** [comment]
Thanks for the Code. A great project.
Vielen Dank, dass Du den Code teilst.
