### ISSUE TITLE
Recommondations for SD Card

### ISSUE THREAD

**Issue by FrankUlbrich** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#4]
Hi Bjorn,
I own a M5STACK FIRE now and would like to start with your great Network-Tester Project.
The code now compiles fine and I have it running with an LoRaWAN Shiled and GPS Shield.
I changed the Serial PINS for the LoRa modul and added an SMA pigtail for the antenna.

No I struggle with the SD Card.
I user an 4GB SD card which is FAT32 formatted.
Unfortunatelly nothing is recorded and I do not get a SD CARD symbol on the screen after a 
GPS Fix.
The FAT32 SD Card is usable in my Laptop.

Do you have a hint, where to look after ?

Mit freundlichen Grüßen
Frank

**Comment by Bjoerns-TB** [comment]
Hi Frank,

the card has to be inserted before you start the M5Stack. As soon as the M5 has booted you should see the SD symbol. The presence of an SD card is only tested on startup.
You could try the factory test sketch, to see if your card reader works.

**Comment by FrankUlbrich** [comment]
Hallo Björn,

you are right. I used the ARDUINO "Factory Test Sketch" to test the M5STACK.
The problem is sorted out now.

not working SD Card : Transcend HC 6 4GB FAT32
       working SD Card : SanDisk Ultra HC1 (10) 16GB FAT32

Vielen Dank für den Hinweis, hätte ich auch selbst drauf kommen können.
Frank

**Comment by FrankUlbrich** [comment]
TOP
