### ISSUE TITLE
Board

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#7]
Hallo,
egal was ich an Board einstelle er macht es nicht. 
Ich habe ein M5Stack Fire.

C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:595:61: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     else if(command == FORCE)sendCommand("AT+JOIN=FORCE\r\n"); 
                                                             ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceLowPower()':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:618:34: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+LOWPOWER\r\n");
                                  ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'void LoRaWanClass::sendDevicePing()':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:627:25: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT\r\n");
                         ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceReset()':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:636:31: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+RESET\r\n");
                               ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceDefault()':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:645:43: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+FDEFAULT=RISINGHF\r\n");
                                           ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'void LoRaWanClass::initP2PMode(short unsigned int, _spreading_factor_t, _band_width_t, unsigned char, unsigned char, short int)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:658:35: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+MODE=TEST\r\n");
                                   ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:662:38: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+TEST=RXLRPKT\r\n");
                                      ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'bool LoRaWanClass::transferPacketP2PMode(char*, unsigned char)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:670:37: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+TEST=TXLRSTR,\"");
                                     ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:672:25: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("\"\r\n");
                         ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:680:53: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     return waitForResponse("+TEST: TX DONE", timeout);
                                                     ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'bool LoRaWanClass::transferPacketP2PMode(unsigned char*, unsigned char, unsigned char)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:687:37: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("AT+TEST=TXLRPKT,\"");
                                     ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:693:25: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommand("\"\r\n");
                         ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:701:53: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     return waitForResponse("+TEST: TX DONE", timeout);
                                                     ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'short int LoRaWanClass::receivePacketP2PMode(unsigned char*, int, short int*, unsigned char)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:709:77: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     sendCommandAndWaitForResponse("AT+TEST=RXLRPKT\r\n", "+TEST: RXLRPKT", 2);
                                                                             ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:709:77: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'short int LoRaWanClass::receivePacket(char*, int, short int*, float*, short int*)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:392:43: warning: 'tmp' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 result = result * 16 + tmp;
                                           ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp: In member function 'short int LoRaWanClass::receivePacketP2PMode(unsigned char*, int, short int*, unsigned char)':
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\LoRaWan.cpp:751:43: warning: 'tmp' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 result = result * 16 + tmp;
                                           ^
C:\Users\laval\Documents\Arduino\libraries\M5Stack-master\src\utility\In_eSPI.cpp:4307:17: warning: 'char_count' defined but not used [-Wunused-variable]
 static uint32_t char_count = 0;
                 ^
C:\Users\laval\Documents\Arduino\libraries\M5_UI-master\M5_UI.cpp: In function 'void UIDrawSelectbox(int)':
C:\Users\laval\Documents\Arduino\libraries\M5_UI-master\M5_UI.cpp:759:9: warning: unused variable 'selectedId' [-Wunused-variable]
     int selectedId = 0;
         ^
C:\Users\laval\Documents\Arduino\libraries\M5_UI-master\M5_UI.cpp: In function 'String UIOptionValue(String*)':
C:\Users\laval\Documents\Arduino\libraries\M5_UI-master\M5_UI.cpp:420:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^

Replace the original files LoraWan.h and LoRaWan.cpp
Hab ich gemacht.
Danke

**Comment by Bjoerns-TB** [comment]
Hi,

ich kann das Problem nicht nachstellen. Ich habe alles frisch heruntergeladen und der Sketch kompiliert. (Arduino 1.8.13, M5Stack 0.3.1)
Hast du dir das Repo als ZIP heruntergeladen oder evetuell per Copy Paste?

Grüße,
Björn

**Comment by Lordcybertracker** [comment]
Ich hab mir das Repo gezogen.
Aber ich Installiere es auch noch mal neu.

**Comment by Lordcybertracker** [comment]
Nach der Neuinstallation ging es.
