### ISSUE TITLE
Eingabe TTN Daten und Einstellungen für FIre mit GPS

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#8]
Hallo,

ich muss Node Daten ja unter:
 lora.init(); 
eingeben. 

// void setId(char *DevAddr, char *DevEUI, char *AppEUI);
    lora.setId("yourdeviceaddress", NULL, NULL);            //for ABP
    //lora.setId("ABP-yourdeviceaddress", "OTAA-yourdeviceEUI", "OTAA-yourAppEUI"); //for OTAA

    // setKey(char *NwkSKey, char *AppSKey, char *AppKey);
    lora.setKey("yourNetworkSKey", "yourappSKey", NULL);          //for ABP
    //lora.setKey("ABP-yourNetworkSKey", "ABP-yourappSKey", "OTAAyourAppKey);   //for OTAA
    
    Dort ja nur die Aktiven bei ABP, oder?
Und dann als { 0x70, oder 70B3XXXXXXXXXXX?

Für den Fire mit GPS passt ja dein Code oder muss ich irgendwas umstellen?
Danke

**Comment by Bjoerns-TB** [comment]
Genau, die zwei Zeilen für ABP reichen.
Die Keys werden als 70B3... eingetragen, einfach copy & paste.

Da das GPS und LoRaWAN Modul die gleichen Ports verwenden, musst du diese am LoRaWAN Modul umlöten.

**Comment by Lordcybertracker** [comment]
Danke,
hättest du davon vielleicht ein Foto?
Muß ich sehen ob ich das hin bekomme. Ansonsten ohne GPS.

**Comment by Lordcybertracker** [comment]
Klappt leider nicht
![stack](https://user-images.githubusercontent.com/52379353/102812446-4def1880-43c7-11eb-8e56-72af219b45c1.jpg)

// void setId(char *DevAddr, char *DevEUI, char *AppEUI);
    lora.setId("2601XXXXX", NULL, NULL);            //for ABP
    //lora.setId("ABP-yourdeviceaddress", "OTAA-yourdeviceEUI", "OTAA-yourAppEUI"); //for OTAA

    // setKey(char *NwkSKey, char *AppSKey, char *AppKey);
    lora.setKey("EFCC95CXXXXXXXXXX1", "CE14XXXXXXX", NULL);          //for ABP
    //lora.setKey("ABP-yourNetworkSKey", "ABP-yourappSKey", "OTAAyourAppKey);   //for OTAA

Das sollte ja jetzt stimmen.

Ich hab jetzt die lorawan,h angepaßt in:
#define SerialUSB   Serial
//#define SerialLoRa  Serial1     //used with GPS module and changed UART port for LoRaWAN module
#define SerialLoRa  Serial2   //used this if unchanged UART port for LoRaWAN module and without GPS module

**Comment by Lordcybertracker** [comment]
Ich sehe gerade mein Lora Modul ist anders aufgebaut auch anderer Chip.
Die Lötbrücken wie auf deinen Fotos habe ich nicht. Allerdings habe ich welche bei 25 35

AM GPS Modul habe ich allerdings die Brücke. um auf 2 3 zu gehen.

**Comment by Bjoerns-TB** [comment]
Das Modul kannst hierfür nicht verwenden, da es per SPI angeschaltet wird und nicht UART.
Ich nutze das LoRaWAN Modul, du hast anscheinend das LoRa 868.

**Comment by Lordcybertracker** [comment]
> 
> 
> Das Modul kannst hierfür nicht verwenden, da es per SPI angeschaltet wird und nicht UART.
> Ich nutze das LoRaWAN Modul, du hast anscheinend das LoRa 868.

AH DANKE GENAU. Das ist es. Muß ich mal sehen wo ich das in D bekomme. Das andere sende ich dann zurück.
Hast du zufällig eine Quelle in Deutschland?

**Comment by Bjoerns-TB** [comment]
Leider nein, hab es damals über Ali bestellt.

**Comment by Lordcybertracker** [comment]
Ist leider nirgends mehr zu bekommen EOL
Abgekündigt.
Schade hätte genau deinen Aufbau Dringend für ausmessen GW und Nodes benötigt.

**Comment by Lordcybertracker** [comment]
Warst du vllt bereit das anzupassen. Das Lora868 Modul würde ich dir auch per Paypal Sponsern.
Ich denke mal wird noch anderen so gehen die es gerne nachbauen würden aber durch das EOL nicht können.

**Comment by Bjoerns-TB** [comment]
Ich habe mir mal eines bestellt, mal schauen was damit geht.

Es wird jedenfalls ein Draht eingelötet werden müssen:
https://github.com/cyberman54/ESP32-Paxcounter/issues/537

Und den LinkCheckMode kann ich dann wohl auch nicht liefern. 

Warten wir es mal ab, ich werde jedenfalls was machen, es wird aber erst mal etwas dauern.

**Comment by Lordcybertracker** [comment]
OK. vielen Dank.

**Comment by Bjoerns-TB** [comment]
Noch nicht 100%ig fertig aber nutzbar.
[M5Stack-LoRa-868-Network-Tester](https://github.com/Bjoerns-TB/M5Stack-LoRa-868-Network-Tester)
