### ISSUE TITLE
COM.LoRaWAN Module operability

### ISSUE THREAD

**Issue by maartenvanderhoef** [Bjoerns-TB/M5Stack-LoRaWAN-Network-Tester#9]
Hi Björn,

Would your code work with the "COM.LoRaWAN Module" ?

**Comment by Bjoerns-TB** [comment]
Hi,

no it would not. The AT commands used by both modules are very different. Currently my COM.LoRaWAN Module is on its way to my workbench and i will try to release an version for it.
